In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('mlmodel.xlsx')

In [3]:
df

Acreage  landvalue  buildingvalue  totalvalue  bedrooms  halfbath  \
0         0.20     125000         627400      781800       4.0       1.0   
1         0.16     125000         136400      261400       3.0       0.0   
2         0.16     125000         136400      261400       3.0       0.0   
3         0.19     125000         305000      430000       3.0       0.0   
4         0.19     125000         305000      430000       3.0       0.0   
...        ...        ...            ...         ...       ...       ...   
25964     0.30      27000          72900      101500       3.0       0.0   
25965    11.93     214700              0      214700       NaN       NaN   
25966     9.00      40500              0       40500       NaN       NaN   
25967    17.54     315700              0      315700       NaN       NaN   
25968     3.02      53900          61600      138400       2.0       0.0   

       fullbath  saleprice  
0           3.0     800000  
1           2.0     350000  
2           2.0     372900  
3           3.0     435000  
4           3.0     503000  
...         ...        ...  
25964       2.0     118900  
25965       NaN     430000  
25966       NaN      32600  
25967       NaN     900000  
25968       1.0     143500  

[25969 rows x 8 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25969 entries, 0 to 25968
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Acreage        25969 non-null  float64
 1   landvalue      25969 non-null  int64  
 2   buildingvalue  25969 non-null  int64  
 3   totalvalue     25969 non-null  int64  
 4   bedrooms       24112 non-null  float64
 5   halfbath       24099 non-null  float64
 6   fullbath       24230 non-null  float64
 7   saleprice      25969 non-null  int64  
dtypes: float64(4), int64(4)
memory usage: 1.6 MB


In [5]:
df.describe()

Acreage     landvalue  buildingvalue    totalvalue      bedrooms  \
count  25969.000000  2.596900e+04   2.596900e+04  2.596900e+04  24112.000000   
mean       0.499375  6.914498e+04   1.608887e+05  2.325590e+05      3.090246   
std        1.571793  1.061174e+05   2.069547e+05  2.812663e+05      0.853152   
min        0.010000  1.000000e+02   0.000000e+00  1.000000e+02      0.000000   
25%        0.180000  2.100000e+04   7.600000e+04  1.028000e+05      3.000000   
50%        0.270000  2.880000e+04   1.114000e+05  1.486000e+05      3.000000   
75%        0.450000  6.000000e+04   1.808000e+05  2.686000e+05      3.000000   
max      160.060000  2.772000e+06   1.297180e+07  1.394040e+07     11.000000   

           halfbath      fullbath     saleprice  
count  24099.000000  24230.000000  2.596900e+04  
mean       0.283912      1.886339  2.809766e+05  
std        0.487944      0.961880  3.748996e+05  
min        0.000000      0.000000  5.000000e+01  
25%        0.000000      1.000000  1.220000e+05  
50%        0.000000      2.000000  1.840000e+05  
75%        1.000000      2.000000  3.250000e+05  
max        3.000000     10.000000  1.235000e+07

In [6]:
df.dropna(inplace=True)

In [8]:
df.corr()

Acreage  landvalue  buildingvalue  totalvalue  bedrooms  \
Acreage        1.000000   0.326249       0.221721    0.287596  0.150688   
landvalue      0.326249   1.000000       0.614267    0.822659  0.342384   
buildingvalue  0.221721   0.614267       1.000000    0.953448  0.447465   
totalvalue     0.287596   0.822659       0.953448    1.000000  0.452261   
bedrooms       0.150688   0.342384       0.447465    0.452261  1.000000   
halfbath       0.054040   0.187214       0.379159    0.343442  0.194003   
fullbath       0.218022   0.539128       0.646844    0.670669  0.613727   
saleprice      0.285663   0.743418       0.728798    0.809669  0.373216   

               halfbath  fullbath  saleprice  
Acreage        0.054040  0.218022   0.285663  
landvalue      0.187214  0.539128   0.743418  
buildingvalue  0.379159  0.646844   0.728798  
totalvalue     0.343442  0.670669   0.809669  
bedrooms       0.194003  0.613727   0.373216  
halfbath       1.000000  0.089546   0.252372  
fullbath       0.089546  1.000000   0.550225  
saleprice      0.252372  0.550225   1.000000

In [37]:
df.drop(df[df['bedrooms']==11].index, inplace=True)

In [38]:
df['bedrooms'].value_counts()

3.0     12753
2.0      5088
4.0      4819
5.0       870
6.0       243
1.0       102
0.0        43
7.0        35
8.0        22
9.0         2
10.0        2
Name: bedrooms, dtype: int64

In [41]:
df.reset_index(drop=True,inplace=True)

### Train Test Split

In [42]:
from sklearn.model_selection import StratifiedShuffleSplit

In [43]:
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(df, df['bedrooms']):
    df_train_set = df.loc[train_index]
    df_test_set = df.loc[test_index]

In [44]:
df_train_set.describe()

Acreage     landvalue  buildingvalue    totalvalue      bedrooms  \
count  19183.000000  1.918300e+04   1.918300e+04  1.918300e+04  19183.000000   
mean       0.456603  6.888761e+04   1.718665e+05  2.434417e+05      3.089715   
std        0.803547  1.017787e+05   1.901088e+05  2.685480e+05      0.854392   
min        0.040000  9.000000e+02   0.000000e+00  1.260000e+04      0.000000   
25%        0.190000  2.200000e+04   8.360000e+04  1.095000e+05      3.000000   
50%        0.270000  2.990000e+04   1.173000e+05  1.547000e+05      3.000000   
75%        0.450000  6.030000e+04   1.888000e+05  2.782000e+05      3.000000   
max       47.500000  1.869000e+06   5.824300e+06  6.402600e+06     10.000000   

           halfbath      fullbath     saleprice  
count  19183.000000  19183.000000  1.918300e+04  
mean       0.284418      1.891414  2.739408e+05  
std        0.487793      0.955010  2.924879e+05  
min        0.000000      0.000000  1.000000e+02  
25%        0.000000      1.000000  1.250000e+05  
50%        0.000000      2.000000  1.850000e+05  
75%        1.000000      2.000000  3.249210e+05  
max        3.000000     10.000000  7.200000e+06

In [45]:
df_train_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19183 entries, 306 to 12619
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Acreage        19183 non-null  float64
 1   landvalue      19183 non-null  int64  
 2   buildingvalue  19183 non-null  int64  
 3   totalvalue     19183 non-null  int64  
 4   bedrooms       19183 non-null  float64
 5   halfbath       19183 non-null  float64
 6   fullbath       19183 non-null  float64
 7   saleprice      19183 non-null  int64  
dtypes: float64(4), int64(4)
memory usage: 1.3 MB


In [46]:
df_test_set['bedrooms'].value_counts()

3.0    2551
2.0    1018
4.0     964
5.0     174
6.0      49
1.0      20
0.0       9
7.0       7
8.0       4
Name: bedrooms, dtype: int64

In [47]:
df_train_set['bedrooms'].value_counts()

3.0     10202
2.0      4070
4.0      3855
5.0       696
6.0       194
1.0        82
0.0        34
7.0        28
8.0        18
10.0        2
9.0         2
Name: bedrooms, dtype: int64

## Crearting Pipeline

In [48]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [49]:
df_features = df_train_set.drop('bedrooms',axis=1)
df_train_labels = df_train_set['bedrooms'].copy()

In [50]:
my_pipeline = Pipeline([('imputer',SimpleImputer(strategy='median')),
                      ('std_scaler', StandardScaler())])

In [51]:
df_tr = my_pipeline.fit_transform(df_features)

In [52]:
df_tr

array([[-0.4189078 , -0.45086853,  0.2968562 , ...,  1.46701459,
         0.11370415,  0.31133434],
       [-0.20734024, -0.29857334,  0.32368365, ..., -0.58308673,
        -0.93343302,  0.24295367],
       [ 0.63892998,  0.649587  , -0.2591557 , ..., -0.58308673,
         0.11370415,  0.19166817],
       ...,
       [-0.29445629, -0.0381977 , -0.00403198, ..., -0.58308673,
         0.11370415,  0.0999355 ],
       [-0.23223054, -0.43613029, -0.53532056, ..., -0.58308673,
         0.11370415, -0.44085304],
       [-0.28201114, -0.38209006, -0.49113418, ..., -0.58308673,
        -0.93343302, -0.18442552]])

In [53]:
df_train_labels

306      3.0
4965     3.0
23875    3.0
18510    2.0
18084    4.0
        ... 
1647     4.0
13131    3.0
1705     3.0
16167    3.0
12619    2.0
Name: bedrooms, Length: 19183, dtype: float64

### Selecting a desired model

In [54]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

### Training Model

In [55]:
# model = DecisionTreeRegressor()
# model = LinearRegression()
model = RandomForestRegressor()
model.fit(df_tr,df_train_labels)

RandomForestRegressor()

### Predicting values

In [56]:
x = df_features.iloc[:5]
y= df_train_labels.iloc[:5]

In [57]:
prep_data = my_pipeline.transform(x)

In [58]:
model.predict(prep_data)

array([3.01, 2.89, 2.84, 2.2 , 4.06])

In [59]:
list(y)

[3.0, 3.0, 3.0, 2.0, 4.0]

### Evaluating model

In [60]:
from sklearn.metrics import mean_squared_error
predictions = model.predict(df_tr)
mse = mean_squared_error(df_train_labels,predictions)
rmse = np.sqrt(mse)
rmse

0.23114583044695744

In [61]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, df_tr, df_train_labels, scoring='neg_mean_squared_error', cv=10)
rmse = np.sqrt(-scores)
rmse

array([0.59817788, 0.63111244, 0.62844905, 0.64128655, 0.61411907,
       0.62866179, 0.60261816, 0.62308476, 0.60681797, 0.62151099])

In [62]:
def print_scores(scores):
    print("scores:",scores)
    print('mean',scores.mean())
    print('Satndard deviation', scores.std())


In [63]:
print_scores(rmse)

scores: [0.59817788 0.63111244 0.62844905 0.64128655 0.61411907 0.62866179
 0.60261816 0.62308476 0.60681797 0.62151099]
mean 0.6195838657376719
Satndard deviation 0.013113992739576726


## Saving the model

In [64]:
from joblib import dump,load
dump(model, 'housing.joblib')

['housing.joblib']

## testing model on test data

In [65]:
xTst = df_test_set.drop('bedrooms',axis=1)
yTst = df_test_set['bedrooms'].copy()
xTstPrep = my_pipeline.transform(xTst)
finalPredictions = model.predict(xTstPrep)
final_mse = mean_squared_error(yTst,finalPredictions)
final_Smse = np.sqrt(final_mse)

final_Smse

0.6232145974933305

In [66]:
finalPredictions[:5]

array([3.03, 3.02, 2.12, 2.57, 3.88])

In [68]:
print(list(yTst.iloc[:5]))

[2.0, 3.0, 2.0, 4.0, 3.0]
